import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet"
      />
      <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
      <link rel="stylesheet" href="assets/css/fontawesome.css" />
      <link rel="stylesheet" href="assets/css/templatemo-woox-travel.css" />
      <link rel="stylesheet" href="assets/css/owl.css" />
      <link rel="stylesheet" href="assets/css/animate.css" />
      <link
        rel="stylesheet"
        href="https://unpkg.com/swiper@7/swiper-bundle.min.css"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
        <script src="assets/js/isotope.min.js"></script>
        <script src="assets/js/owl-carousel.js"></script>
        <script src="assets/js/wow.js"></script>
        <script src="assets/js/tabs.js"></script>
        <script src="assets/js/popup.js"></script>
        <script src="assets/js/custom.js"></script>
        {/* <!-- ***** Header Area Start ***** --> */}
        <header class="header-area header-fixed">
          <div class="container">
            <div class="row">
              <div class="col-12">
                <nav class="main-nav">
                  {/* <!-- ***** Logo Start ***** --> */}
                  <a href="index.html" class="logo">
                    <img src="assets/images/logo.png" alt="" />
                  </a>
                  {/* <!-- ***** Logo End ***** --> */}
                  {/* <!-- ***** Menu Start ***** --> */}
                  <ul class="nav">
                    <li>
                      <Link href="/" class="active">
                        Home
                      </Link>
                    </li>
                    <li>
                      <Link href="/about">About</Link>
                    </li>
                    <li>
                      <Link href="/deals">Deals</Link>
                    </li>
                    <li>
                      <Link href="/reservation">Reservation</Link>
                    </li>
                    <li>
                      <Link href="/reservation">Book Yours</Link>
                    </li>
                  </ul>
                  <a class="menu-trigger">
                    <span>Menu</span>
                  </a>
                  {/* <!-- ***** Menu End ***** --> */}
                </nav>
              </div>
            </div>
          </div>
        </header>
        {/* <!-- ***** Header Area End ***** --> */}
        {children}
        {/* <!-- ***** Footer Area Start ***** --> */}
        <div class="call-to-action">
          <div class="container">
            <div class="row">
              <div class="col-lg-8">
                <h2>Are You Looking To Travel ?</h2>
                <h4>Make A Reservation By Clicking The Button</h4>
              </div>
              <div class="col-lg-4">
                <div class="border-button">
                  <a href="reservation.html">Book Yours Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <footer>
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <p>
                  Copyright © 2036 <a href="#">WoOx Travel</a> Company. All
                  rights reserved.
                  <br />
                  Design:{" "}
                  <a
                    href="https://templatemo.com"
                    target="_blank"
                    title="free CSS templates"
                  >
                    TemplateMo
                  </a>
                </p>
              </div>
            </div>
          </div>
        </footer>
        {/* <!-- ***** Footer Area End ***** --> */}
      </body>
    </html>
  );
}
